### PR TITLE
Pjtp/feat/selected cafes endpoint

### PR DESCRIPTION
**Pull request by pablisch**
Created an endpoint to return matching cafes based on facilities available.

**NOTE: This includes the current Cafe Model and adds a necessary change. It makes sense to make any further changes to the Cafe Model from this branch.**

The endpoint is complete as far as can be done at this time.

Future adaptions:

- [x] Minor edit when required facilities is implemented into Cafe Model.
- [ ] Significant logic addition when a location is provided to the controller function to return only cafes within the required distance.

It seems helpful to merge this currently working branch into main for group visibilty.

### CODE REVIEW

**Review by kikilondon — CHANGES_REQUESTED** [review]
I haven't review the code, but I run it on pOstman and it doesn't return the cafes with the facilities requested.

**Comment by pablisch** [comment]
I had not pushed some changes and also postman tests needed revision as the data in the database had changed, e.g. outdoor space became outdoor area.

**Review by kikilondon — COMMENTED** [review]
PostMan tests don't work anymore. The server doesn't find the "cafes" collection; the version requested (v1.0) from the endpoint URL is different than that in the MongoDB collection (v.0). OR maybe I cannot request anymore as I have reached the limited daily requests in Postman for today.

**Review by kikilondon — APPROVED** [review]

**Review by kikilondon — DISMISSED** [review]

**Review by kikilondon — APPROVED** [review]
:)

**Review by kikilondon — APPROVED** [review]
Test to approve previous request changes

**Review by kikilondon — DISMISSED** [review]
Test

**Review by kikilondon — APPROVED** [review]
test review

**Pull request closed without merging**
